export type Locale = "en" | "bn";
export const dictionaries = {
  en: {
    home: "Home", shop: "Shop", cart: "Cart", search: "Search", searchProducts: "Search products", browseProducts: "Browse products",
    skip: "Skip to content", tagline: "Shop smart. Live better.", whatsapp: "Contact on WhatsApp", emailSupport: "Email support",
    codOff: "Cash on Delivery is temporarily unavailable.", codConditional: "Cash on Delivery orders are available only when shipping rates are configured.", noOnlinePayment: "No online payment is collected.",
    heroEyebrow: "Welcome to Monechai", heroTitle: "Shop Smart,", heroTitleSecond: "Live Better.", heroText: "Explore our growing collection. Browse products and check delivery availability at checkout.", browseShop: "Browse the shop",
    explore: "Explore Monechai", find: "Find what suits you.", browseCategories: "Browse categories", browseCategoriesText: "Find products that interest you.", compareOptions: "Compare options", compareOptionsText: "Review prices, details and availability.", checkDelivery: "Check delivery", checkDeliveryText: "Choose a delivery area and see current totals before placing a COD order.",
    byCategory: "Shop by category", seeAll: "See all", featured: "Featured products", exploreProducts: "Explore products", comingSoon: "Products coming soon", comingSoonText: "Our catalog has no published products yet. Please check back later.",
    shopTitle: "Shop products", shopIntro: "Find products by name or category. Cash on Delivery checkout requires configured delivery fees.", category: "Category", allCategories: "All categories", unknownCategory: "Unknown category", sort: "Sort by", newest: "Newest", lowHigh: "Price: low to high", highLow: "Price: high to low", filters: "Apply filters", found: "products found", noPage: "No products on this page", noResults: "No products found", tryAnother: "Try another search or category.", publishedHere: "Published products will appear here when available.", browseAll: "Browse all products", previous: "Previous", next: "Next", page: "Page", of: "of",
    unavailable: "Unavailable", available: "Available", currentlyUnavailable: "Currently unavailable", details: "View details", imageSoon: "Image coming soon", imageUnavailable: "Image not available for", previously: "Previously", about: "About this product", options: "Options", chooseOption: "Choose an option", outOfStock: "out of stock", added: "Added to cart", add: "Add to cart", deliveryNotice: "Delivery fees are confirmed at checkout. Cash on Delivery only; ordering is unavailable until delivery rates are configured.", continueBrowsing: "Continue browsing",
    checkoutTitle: "Cart and checkout", checkoutIntro: "Cash on Delivery. Prices and availability are verified again when you place an order.", orderReceived: "Order received", orderSaved: "Your Cash on Delivery order was saved successfully.", reference: "Reference", totalDelivery: "Total including delivery", status: "Status", privateLink: "Save this private link to check the order. It cannot be recovered from a public order number.", continueShopping: "Continue shopping",
    yourCart: "Your cart", emptyCart: "Your cart is empty", checkingItem: "Checking item…", quantity: "Quantity", remove: "Remove", closeCart: "Close cart", cartError: "Cart details are temporarily unavailable. Retry at checkout.", finalCheck: "Final price, delivery and availability are checked at checkout.", proceed: "Proceed to checkout", yourItems: "Your items", each: "each", removeOrReduce: "Unavailable — remove or reduce quantity", deliveryArea: "Delivery area", insideDhaka: "Inside Dhaka", outsideDhaka: "Outside Dhaka", subtotal: "Subtotal", delivery: "Delivery", estimatedTotal: "Estimated total", areaFeesMissing: "Delivery fees for this area are not configured yet. Orders cannot be placed.", reviewItems: "Review your items before continuing.", deliveryDetails: "Delivery details", fullName: "Full name", mobile: "Bangladesh mobile number", street: "Street address", area: "Area", note: "Delivery note (optional)", paymentCod: "Payment: Cash on Delivery. No online payment is collected.", placing: "Placing order…", placeOrder: "Place COD order", loadingCart: "Loading cart…", checkoutError: "Checkout unavailable; please retry.",
    itemUnavailable: "An item is no longer available. Refresh your cart.", insufficientStock: "An item has insufficient stock. Refresh your cart.", shippingUnavailable: "Delivery to this zone is not configured yet.", retryCheckout: "Start a new checkout for changed details.", storeError: "Storefront unavailable", storeErrorText: "We couldn’t load the catalog. Please try again later.", tryAgain: "Try again",
  },
  bn: {
    home: "হোম", shop: "দোকান", cart: "কার্ট", search: "খুঁজুন", searchProducts: "পণ্য খুঁজুন", browseProducts: "পণ্য দেখুন",
    skip: "মূল অংশে যান", tagline: "বেছে নিন সহজে।", whatsapp: "হোয়াটসঅ্যাপে যোগাযোগ", emailSupport: "ইমেইলে যোগাযোগ",
    codOff: "ক্যাশ অন ডেলিভারি সাময়িকভাবে বন্ধ আছে।", codConditional: "ডেলিভারি খরচ নির্ধারিত থাকলেই ক্যাশ অন ডেলিভারি অর্ডার করা যাবে।", noOnlinePayment: "অনলাইনে কোনো পেমেন্ট নেওয়া হয় না।",
    heroEyebrow: "মোনেচাইয়ে স্বাগতম", heroTitle: "সহজে কিনুন,", heroTitleSecond: "ভালো থাকুন।", heroText: "আমাদের পণ্য দেখুন এবং চেকআউটে ডেলিভারি সুবিধা যাচাই করুন।", browseShop: "পণ্য দেখুন",
    explore: "মোনেচাই দেখুন", find: "আপনার পছন্দের পণ্য খুঁজুন।", browseCategories: "ক্যাটাগরি দেখুন", browseCategoriesText: "পছন্দের পণ্য খুঁজে নিন।", compareOptions: "বিকল্প তুলনা করুন", compareOptionsText: "দাম, বিবরণ ও প্রাপ্যতা দেখুন।", checkDelivery: "ডেলিভারি যাচাই করুন", checkDeliveryText: "ক্যাশ অন ডেলিভারি অর্ডারের আগে এলাকা বেছে মোট খরচ দেখুন।",
    byCategory: "ক্যাটাগরি অনুযায়ী দেখুন", seeAll: "সব দেখুন", featured: "নির্বাচিত পণ্য", exploreProducts: "পণ্য দেখুন", comingSoon: "পণ্য শিগগির আসছে", comingSoonText: "এখনো কোনো প্রকাশিত পণ্য নেই। পরে আবার দেখুন।",
    shopTitle: "পণ্য দেখুন", shopIntro: "নাম বা ক্যাটাগরি দিয়ে পণ্য খুঁজুন। ক্যাশ অন ডেলিভারি চেকআউটের জন্য ডেলিভারি খরচ নির্ধারিত থাকতে হবে।", category: "ক্যাটাগরি", allCategories: "সব ক্যাটাগরি", unknownCategory: "অজানা ক্যাটাগরি", sort: "সাজান", newest: "নতুন আগে", lowHigh: "দাম: কম থেকে বেশি", highLow: "দাম: বেশি থেকে কম", filters: "ফিল্টার করুন", found: "টি পণ্য পাওয়া গেছে", noPage: "এই পাতায় পণ্য নেই", noResults: "কোনো পণ্য পাওয়া যায়নি", tryAnother: "অন্য নাম বা ক্যাটাগরি দিয়ে খুঁজুন।", publishedHere: "প্রকাশিত পণ্য এখানে দেখা যাবে।", browseAll: "সব পণ্য দেখুন", previous: "আগের", next: "পরের", page: "পৃষ্ঠা", of: "এর",
    unavailable: "পাওয়া যাচ্ছে না", available: "পাওয়া যাচ্ছে", currentlyUnavailable: "এখন পাওয়া যাচ্ছে না", details: "বিস্তারিত দেখুন", imageSoon: "ছবি শিগগির আসছে", imageUnavailable: "ছবি পাওয়া যাচ্ছে না:", previously: "আগের দাম", about: "পণ্যের বিবরণ", options: "বিকল্প", chooseOption: "বিকল্প বাছুন", outOfStock: "স্টক নেই", added: "কার্টে যোগ হয়েছে", add: "কার্টে যোগ করুন", deliveryNotice: "চেকআউটে ডেলিভারি খরচ নিশ্চিত করা হবে। শুধু ক্যাশ অন ডেলিভারি; ডেলিভারি খরচ নির্ধারিত না থাকলে অর্ডার করা যাবে না।", continueBrowsing: "আরও পণ্য দেখুন",
    checkoutTitle: "কার্ট ও চেকআউট", checkoutIntro: "ক্যাশ অন ডেলিভারি। অর্ডারের সময় দাম ও প্রাপ্যতা আবার যাচাই করা হবে।", orderReceived: "অর্ডার নেওয়া হয়েছে", orderSaved: "আপনার ক্যাশ অন ডেলিভারি অর্ডার সংরক্ষিত হয়েছে।", reference: "অর্ডার নম্বর", totalDelivery: "ডেলিভারিসহ মোট", status: "অবস্থা", privateLink: "অর্ডার দেখতে এই ব্যক্তিগত লিংকটি সংরক্ষণ করুন। শুধু অর্ডার নম্বর দিয়ে লিংকটি পাওয়া যাবে না।", continueShopping: "আরও কেনাকাটা করুন",
    yourCart: "আপনার কার্ট", emptyCart: "কার্ট খালি", checkingItem: "পণ্য যাচাই হচ্ছে…", quantity: "পরিমাণ", remove: "সরান", closeCart: "কার্ট বন্ধ করুন", cartError: "কার্টের তথ্য এখন পাওয়া যাচ্ছে না। চেকআউটে আবার চেষ্টা করুন।", finalCheck: "চূড়ান্ত দাম, ডেলিভারি ও প্রাপ্যতা চেকআউটে যাচাই করা হবে।", proceed: "চেকআউটে যান", yourItems: "আপনার পণ্য", each: "প্রতিটি", removeOrReduce: "পাওয়া যাচ্ছে না — সরান বা পরিমাণ কমান", deliveryArea: "ডেলিভারি এলাকা", insideDhaka: "ঢাকার ভিতরে", outsideDhaka: "ঢাকার বাইরে", subtotal: "পণ্যের মোট", delivery: "ডেলিভারি", estimatedTotal: "আনুমানিক মোট", areaFeesMissing: "এই এলাকার ডেলিভারি খরচ এখনো নির্ধারিত হয়নি। অর্ডার করা যাবে না।", reviewItems: "এগোনোর আগে পণ্যগুলো যাচাই করুন।", deliveryDetails: "ডেলিভারির তথ্য", fullName: "পূর্ণ নাম", mobile: "বাংলাদেশি মোবাইল নম্বর", street: "বাসার ঠিকানা", area: "এলাকা", note: "ডেলিভারি নোট (ঐচ্ছিক)", paymentCod: "পেমেন্ট: ক্যাশ অন ডেলিভারি। অনলাইনে কোনো পেমেন্ট নেওয়া হয় না।", placing: "অর্ডার হচ্ছে…", placeOrder: "ক্যাশ অন ডেলিভারি অর্ডার করুন", loadingCart: "কার্ট লোড হচ্ছে…", checkoutError: "চেকআউট এখন পাওয়া যাচ্ছে না। আবার চেষ্টা করুন।",
    itemUnavailable: "একটি পণ্য আর পাওয়া যাচ্ছে না। কার্ট নতুন করে দেখুন।", insufficientStock: "একটি পণ্যের পর্যাপ্ত স্টক নেই। কার্ট নতুন করে দেখুন।", shippingUnavailable: "এই এলাকায় ডেলিভারি এখনো চালু হয়নি।", retryCheckout: "তথ্য বদলে থাকলে নতুন চেকআউট শুরু করুন।", storeError: "দোকান এখন পাওয়া যাচ্ছে না", storeErrorText: "পণ্য তালিকা লোড করা যায়নি। পরে আবার চেষ্টা করুন।", tryAgain: "আবার চেষ্টা করুন",
  },
} as const;

export function getDictionary(locale: Locale) { return dictionaries[locale]; }
export function localizedText(locale: Locale, english: string, bangla: string | null | undefined) {
  return locale === "bn" && bangla?.trim() ? bangla : english;
}

const orderStatusLabels = {
  pending_confirmation: { en: "Pending confirmation", bn: "নিশ্চিতকরণের অপেক্ষায়" },
  confirmed: { en: "Confirmed", bn: "নিশ্চিত হয়েছে" },
  packed: { en: "Packed", bn: "প্যাকেট করা হয়েছে" },
  shipped: { en: "Shipped", bn: "পাঠানো হয়েছে" },
  delivered: { en: "Delivered", bn: "ডেলিভারি হয়েছে" },
  cancelled: { en: "Cancelled", bn: "বাতিল হয়েছে" },
} as const;

export function orderStatusLabel(locale: Locale, status: string) {
  return status in orderStatusLabels ? orderStatusLabels[status as keyof typeof orderStatusLabels][locale] : status;
}
